import { Badge, CategoryInfo, GameItem, QnAItem, RewardItem, WasteCategory } from '../types';

export const CATEGORY_MAP: Record<WasteCategory, CategoryInfo> = {
  PET: {
    id: 'PET',
    name: '투명 페트병',
    color: 'emerald-600',
    bgColor: 'bg-emerald-50',
    borderColor: 'border-emerald-300',
    badgeBg: 'bg-emerald-100',
    badgeText: 'text-emerald-800',
    iconName: 'Bottle',
    description: '내용물 비우기 → 라벨 제거 → 압착 후 뚜껑 닫아 투명 페트병 전용함에 배출',
  },
  PLASTIC: {
    id: 'PLASTIC',
    name: '플라스틱류',
    color: 'teal-600',
    bgColor: 'bg-teal-50',
    borderColor: 'border-teal-300',
    badgeBg: 'bg-teal-100',
    badgeText: 'text-teal-800',
    iconName: 'Box',
    description: '이물질 씻어내기, 부속품(스프링, 고무 등) 분리 후 배출',
  },
  VINYL: {
    id: 'VINYL',
    name: '비닐류',
    color: 'purple-600',
    bgColor: 'bg-purple-50',
    borderColor: 'border-purple-300',
    badgeBg: 'bg-purple-100',
    badgeText: 'text-purple-800',
    iconName: 'Layers',
    description: '이물질 없는 맑은 비닐, 흩날리지 않게 모아서 배출 (오염 시 일반쓰레기)',
  },
  PAPER: {
    id: 'PAPER',
    name: '종이류',
    color: 'amber-600',
    bgColor: 'bg-amber-50',
    borderColor: 'border-amber-300',
    badgeBg: 'bg-amber-100',
    badgeText: 'text-amber-800',
    iconName: 'FileText',
    description: '택배 상자 테이프 및 철심 제거, 물기에 젖지 않은 종이만 배출',
  },
  PAPER_PACK: {
    id: 'PAPER_PACK',
    name: '종이팩 (우유팩/두유팩)',
    color: 'amber-700',
    bgColor: 'bg-orange-50',
    borderColor: 'border-orange-300',
    badgeBg: 'bg-orange-100',
    badgeText: 'text-orange-800',
    iconName: 'Milk',
    description: '일반 종이와 다름! 내용물 헹군 뒤 펼쳐서 바짝 말려 종이팩 전용함 배출',
  },
  GLASS: {
    id: 'GLASS',
    name: '유리병',
    color: 'sky-600',
    bgColor: 'bg-sky-50',
    borderColor: 'border-sky-300',
    badgeBg: 'bg-sky-100',
    badgeText: 'text-sky-800',
    iconName: 'Wine',
    description: '상표 라벨 유지, 뚜껑 분리, 깨지지 않게 배출 (깨진 유리는 불연성 쓰레기봉투)',
  },
  CAN_METAL: {
    id: 'CAN_METAL',
    name: '캔/고철류',
    color: 'slate-600',
    bgColor: 'bg-slate-100',
    borderColor: 'border-slate-300',
    badgeBg: 'bg-slate-200',
    badgeText: 'text-slate-800',
    iconName: 'Shield',
    description: '내용물 비우기, 구멍 뚫어 부탄가스 잔량 제거, 압착 배출',
  },
  STYROFOAM: {
    id: 'STYROFOAM',
    name: '스티로폼',
    color: 'indigo-600',
    bgColor: 'bg-indigo-50',
    borderColor: 'border-indigo-300',
    badgeBg: 'bg-indigo-100',
    badgeText: 'text-indigo-800',
    iconName: 'Package',
    description: '상표 스티커 및 테이프 제거, 오염이 심한 컵라면 스티로폼은 일반쓰레기',
  },
  GENERAL: {
    id: 'GENERAL',
    name: '일반쓰레기 (종량제)',
    color: 'rose-600',
    bgColor: 'bg-rose-50',
    borderColor: 'border-rose-300',
    badgeBg: 'bg-rose-100',
    badgeText: 'text-rose-800',
    iconName: 'Trash2',
    description: '재활용 불가능한 오염 물품, 영수증, 칫솔, 기저귀, 기름진 종이 등 종량제 봉투 배출',
  },
  E_WASTE: {
    id: 'E_WASTE',
    name: '폐가전 / 폐건전지 / 형광등',
    color: 'violet-600',
    bgColor: 'bg-violet-50',
    borderColor: 'border-violet-300',
    badgeBg: 'bg-violet-100',
    badgeText: 'text-violet-800',
    iconName: 'Zap',
    description: '주민센터/전용 수거함 배출 (소형 가전은 5개 이상 무료 무상방문수거 신청 가능)',
  },
  FOOD: {
    id: 'FOOD',
    name: '음식물 쓰레기',
    color: 'lime-600',
    bgColor: 'bg-lime-50',
    borderColor: 'border-lime-300',
    badgeBg: 'bg-lime-100',
    badgeText: 'text-lime-800',
    iconName: 'Utensils',
    description: '물기 최대한 짜내기. 뼈, 조개껍데기, 씨앗, 달걀껍질은 일반쓰레기!',
  },
};

export const SAMPLE_TEST_PRESETS = [
  {
    id: 'pet_bottle',
    name: '투명 생수 페트병 (라벨 있음)',
    category: 'PET',
    description: '비닐 라벨이 붙어있는 상태의 500ml 투명 생수병',
    samplePrompt: '투명 500ml 생수 페트병입니다. 비닐 상표 라벨이 그대로 부착되어 있고 뚜껑이 닫혀있습니다.',
    imageUrl: 'https://images.unsplash.com/photo-1605600659873-d808a13e4d2a?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'milk_carton',
    name: '세척한 1,000ml 우유팩',
    category: 'PAPER_PACK',
    description: '물로 깔끔히 헹구고 펼쳐서 말린 종이 우유팩',
    samplePrompt: '깨끗하게 씻어 펼쳐 말린 1000ml 우유팩입니다.',
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'pizza_box',
    name: '기름이 묻은 피자 상자',
    category: 'GENERAL',
    description: '기름과 치즈 이물질이 묻은 배달 피자 종이 상자',
    samplePrompt: '기름과 양념 자국이 심하게 남아있는 종이 피자 상자입니다.',
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'coffee_cup',
    name: '아이스 카페라떼 아이스컵 & 빨대',
    category: 'PLASTIC',
    description: '플라스틱 컵, 빨대, 얼음 잔여물이 남아있는 음료 컵',
    samplePrompt: '플라스틱 커피 컵과 빨대입니다. 얼음과 라떼 잔여물이 약간 남아있습니다.',
    imageUrl: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'batteries',
    name: '다 쓴 AA 알칼라인 건전지',
    category: 'E_WASTE',
    description: '리모컨과 시계에서 꺼낸 다 쓴 건전지들',
    samplePrompt: '사용이 끝난 소형 AA/AAA 건전지 모음입니다.',
    imageUrl: 'https://images.unsplash.com/photo-1619725002198-6a689b72f41d?w=600&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_BADGES: Badge[] = [
  {
    id: 'first_scan',
    name: '첫 AI 분리배출',
    description: 'AI 카메라로 쓰레기 배출 방법을 첫 검색했어요.',
    iconName: 'Camera',
    requirement: 'AI 카메라 1회 사용',
    unlocked: true,
    unlockedAt: '2026-07-26',
  },
  {
    id: 'pet_master',
    name: '페트병 순환 마스터',
    description: '라벨 제거 페트병 인증을 3회 성공했어요.',
    iconName: 'Bottle',
    requirement: '투명 페트병 인증 3회',
    unlocked: false,
  },
  {
    id: 'clean_earth',
    name: '깨끗한 지구 지킴이',
    description: '총 5회 이상의 분리수거를 완벽하게 인증했습니다.',
    iconName: 'Globe',
    requirement: '분리수거 인증 5회',
    unlocked: false,
  },
  {
    id: 'streak_3',
    name: '3일 연속 그린 루틴',
    description: '3일 연속으로 올바른 분리배출을 실천했어요.',
    iconName: 'Flame',
    requirement: '연속 인증 3일',
    unlocked: false,
  },
  {
    id: 'game_hero',
    name: '분리배출 오락실 고수',
    description: '미니게임 점수 1,000점 이상을 달성했습니다.',
    iconName: 'Trophy',
    requirement: '게임 점수 1,000점 달성',
    unlocked: false,
  },
  {
    id: 'tree_planter',
    name: '나무 한 그루의 힘',
    description: '포인트로 실제 나무 기부 캠페인에 참여했습니다.',
    iconName: 'TreeTree',
    requirement: '나무 기부 쿠폰 교환',
    unlocked: false,
  },
];

export const INITIAL_REWARDS: RewardItem[] = [
  {
    id: 'bag_coupon_10l',
    title: '종량제 봉투 10L 교환권 (2매)',
    brand: '전국 주민센터 & 편의점',
    category: 'coupon',
    pointsRequired: 500,
    description: '올바른 분리배출을 실천하는 분들을 위한 필수 종량제 봉투 무료 교환 쿠폰',
    badgeTag: '인기 실속형',
    iconName: 'Trash',
  },
  {
    id: 'cu_gift_2000',
    title: 'CU 편의점 2,000원 모바일 금액권',
    brand: 'CU 편의점',
    category: 'voucher',
    pointsRequired: 1500,
    description: '전국 CU 편의점에서 친환경 음료 및 가공식품 구매 시 사용 가능',
    badgeTag: '매일 사용',
    iconName: 'ShoppingBag',
  },
  {
    id: 'tree_donation',
    title: '강원도 숲 조성을 위한 실제 나무 1그루 기부',
    brand: '트리플래닛 / 에코비움 숲',
    category: 'donation',
    pointsRequired: 2000,
    description: '내 이름으로 강원도 산불 피해 지역에 진짜 나무 1그루를 심어 CO2 감소에 기여합니다.',
    badgeTag: '지구 살리기',
    iconName: 'Trees',
  },
  {
    id: 'starbucks_tumbler_discount',
    title: '스타벅스 텀블러/친환경 굿즈 3,000원 할인권',
    brand: '스타벅스 코리아',
    category: 'coupon',
    pointsRequired: 2500,
    description: '다회용 컵 및 친환경 굿즈 구매 시 즉시 할인받을 수 있는 쿠폰',
    badgeTag: '친환경 라이프',
    iconName: 'Coffee',
  },
  {
    id: 'gs25_gift_5000',
    title: 'GS25 편의점 5,000원 모바일 금액권',
    brand: 'GS25',
    category: 'voucher',
    pointsRequired: 3500,
    description: '전국 GS25 매장에서 자유롭게 사용할 수 있는 바코드 모바일 상품권',
    badgeTag: '프리미엄 보상',
    iconName: 'Gift',
  },
];

export const INITIAL_QNA: QnAItem[] = [
  {
    id: 'q1',
    question: '기름이 묻은 피자상자나 치킨상자는 종이로 재활용되나요?',
    category: 'GENERAL',
    answer: '아닙니다! 기름, 양념, 치즈 이물질이 흡수된 종이는 재활용 불가능합니다. 깨끗한 상단 덮개 부위만 잘라내어 종이로 버리고, 기름진 바닥 상자는 일반쓰레기(종량제)에 버려주세요.',
    keyRule: '양념/기름 오염 종이 → 일반쓰레기',
    tags: ['피자상자', '치킨상자', '종이', '기름'],
  },
  {
    id: 'q2',
    question: '우유팩과 두유팩은 일반 종이폐지와 같이 버려도 되나요?',
    category: 'PAPER_PACK',
    answer: '안 됩니다. 우유팩/두유팩(종이팩)은 일반 종이와 달리 내부가 폴리에틸렌(PE)이나 알루미늄으로 코팅되어 있습니다. 물로 헹군 뒤 잘라 펼쳐서 말린 후 [종이팩 전용 수거함]이나 주민센터 휴지 교환 사업을 이용하셔야 합니다.',
    keyRule: '종이팩은 별도 전용 수거함에 배출',
    tags: ['우유팩', '두유팩', '종이팩', '주민센터'],
  },
  {
    id: 'q3',
    question: '깨진 유리창이나 깨진 유리컵은 유리병으로 버려야 하나요?',
    category: 'GENERAL',
    answer: '아닙니다! 깨진 유리는 유색/투명 유리병 재활용 공정에 들어갈 수 없습니다. 신문지나 두꺼운 종이로 여러 겹 감싸서 [불연성 마대자루/특량제 봉투] 또는 일반 쓰레기로 안전하게 버려야 합니다.',
    keyRule: '깨진 유리 → 불연성 마대/안전포장 종량제',
    tags: ['깨진유리', '유리컵', '불연성', '안전'],
  },
  {
    id: 'q4',
    question: '투명 페트병의 뚜껑과 고리는 어떻게 배출하나요?',
    category: 'PET',
    answer: '투명 페트병 본체의 비닐 라벨은 완벽히 떼어 비닐류로 버립니다. 뚜껑과 목에 걸린 플라스틱 고리는 세척 및 압착 후 뚜껑을 다시 닫아서 투명 페트병함에 넣어도 재활용 파쇄 공정에서 비중 차이로 자동 분리됩니다.',
    keyRule: '라벨 제거 필수! 뚜껑은 압착 후 닫아서 배출',
    tags: ['투명페트병', '라벨', '뚜껑', '플라스틱'],
  },
  {
    id: 'q5',
    question: '컵라면 용기(스티로폼)에 빨간 국물 자국이 남아있는데 재활용되나요?',
    category: 'STYROFOAM',
    answer: '햇빛에 며칠 말려 국물 자국이 완전히 사라지고 흰색이 된 스티로폼은 스티로폼 재활용이 가능합니다. 하지만 빨간 국물이 그대로 스며든 스티로폼 용기는 일반쓰레기(종량제)로 버려야 합니다.',
    keyRule: '흰색 스티로폼만 재활용 / 착색 스티로폼 → 일반쓰레기',
    tags: ['컵라면', '스티로폼', '국물자국', '햇빛'],
  },
  {
    id: 'q6',
    question: '스프레이 캔이나 부탄가스 캔은 어떻게 버려야 안전한가요?',
    category: 'CAN_METAL',
    answer: '통풍이 잘되는 야외에서 노즐을 눌러 가스를 완전히 뺀 후, 송곳으로 바닥에 구멍을 1~2개 뚫어 가스를 완전히 배출시킨 뒤 캔류로 배출합니다. (폭발 위험 예방)',
    keyRule: '통풍 좋은 야외 가스 배출 후 구멍 뚫어 캔 배출',
    tags: ['부탄가스', '스프레이', '구멍', '캔류'],
  },
];

export const GAME_ITEMS_POOL: GameItem[] = [
  {
    id: 'g1',
    name: '투명 생수 페트병 (라벨 부착)',
    correctCategory: 'PET',
    icon: '🍾',
    hasLabel: true,
    isDirty: false,
    trickExplanation: '페트병은 비닐 라벨을 먼저 손으로 찢어 떼어내야 합니다!',
  },
  {
    id: 'g2',
    name: '깨끗한 택배 박스 (테이프 부착)',
    correctCategory: 'PAPER',
    icon: '📦',
    hasLabel: true,
    isDirty: false,
    trickExplanation: '택배 상자의 비닐 테이프와 운송장 스티커를 먼저 제거해야 재활용됩니다.',
  },
  {
    id: 'g3',
    name: '기름범벅 양념 피자상자',
    correctCategory: 'GENERAL',
    icon: '🍕',
    hasLabel: false,
    isDirty: true,
    trickExplanation: '기름과 양념이 밴 종이는 재활용 불가능하므로 종량제 일반쓰레기입니다!',
  },
  {
    id: 'g4',
    name: '세척 후 잘라 말린 우유팩',
    correctCategory: 'PAPER_PACK',
    icon: '🥛',
    hasLabel: false,
    isDirty: false,
    trickExplanation: '우유팩은 일반 종이가 아닌 [종이팩 전용함]에 버려야 정상 재활용됩니다.',
  },
  {
    id: 'g5',
    name: '깨끗하게 씻은 음료 유리병',
    correctCategory: 'GLASS',
    icon: '🍾',
    hasLabel: false,
    isDirty: false,
    trickExplanation: '내용물을 비우고 뚜껑을 분리하면 완벽한 유리병 재활용!',
  },
  {
    id: 'g6',
    name: '음식물이 덕지덕지 묻은 배달 용기',
    correctCategory: 'GENERAL',
    icon: '🍱',
    hasLabel: false,
    isDirty: true,
    trickExplanation: '음식물이 씻기지 않는 플라스틱 용기는 일반쓰레기(종량제)로 버려야 합니다.',
  },
  {
    id: 'g7',
    name: '다 쓴 AA 알칼라인 건전지',
    correctCategory: 'E_WASTE',
    icon: '🔋',
    hasLabel: false,
    isDirty: false,
    trickExplanation: '폐건전지는 중금속 오염 방지를 위해 주민센터/아파트 건전지 전용 수거함에 버립니다.',
  },
  {
    id: 'g8',
    name: '이물질 없는 과자 비닐봉지',
    correctCategory: 'VINYL',
    icon: '🛍️',
    hasLabel: false,
    isDirty: false,
    trickExplanation: '깨끗하게 비워진 과자 봉지는 비닐류로 분리배출합니다.',
  },
  {
    id: 'g9',
    name: '내용물 비우고 구멍 뚫은 부탄가스 캔',
    correctCategory: 'CAN_METAL',
    icon: '🥫',
    hasLabel: false,
    isDirty: false,
    trickExplanation: '가스를 빼고 구멍을 뚫은 금속 캔은 캔/고철류로 분리배출!',
  },
  {
    id: 'g10',
    name: '깨진 유리 조각',
    correctCategory: 'GENERAL',
    icon: '🍸',
    hasLabel: false,
    isDirty: true,
    trickExplanation: '깨진 유리는 병 재활용이 불가능하므로 종이에 두껍게 감싸 일반/불연성 쓰레기로 배출합니다.',
  },
];
